namespace: my_namespace
application_name: my_app
service_name: my-app-service
service_port: 80
host: "my_app.example.com"
vlan_id: 1
vlan_name: vlan1
interface_name: eth0
gateway_external_ip: 192.168.1.101
cluster_issuer_name: "letsencrypt-staging"
https_listening_port: 443
isolateNamespace: true
loadBalancerSourceRanges: []