---
# Creates a NetworkAttachmentDefinition for Multus CNI with a static IP in a specific VLAN
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: "{{ .Values.app_name }}-static"
  namespace: "{{ .Release.Namespace }}"
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "{{ .Values.interface_name }}.{{ .Values.vlan_id }}",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "{{ .Values.proxy_address }}/{{ .Values.proxy_cidr }}",
            "gateway": "{{ .Values.proxy_gateway }}"
          }
        ],
        "routes": [
          { "dst": "{{ .Values.proxy_reroute_network }}", "gw": "{{ .Values.proxy_gateway }}" }
        ]
      }
    }
