---
# Create a TLS certificate for the nginx proxy
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.app_name }}-tls"
  namespace: "{{ .Release.Namespace }}"
spec:
  secretName: "{{ .Values.app_name }}-tls"
  issuerRef:
    kind: ClusterIssuer
    name: "{{ .Values.tls.clusterIssuerName }}"
  dnsNames:
  {{- range .Values.tls.hosts }}
    - {{ . | quote }}
  {{- end }}
