---
# IP pool for the Cilium load balancer in the application VLAN
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: "{{ .Values.application_name }}-{{ .Values.vlan_name }}-vlan-pool"
spec:
  blocks:
    - cidr: {{ .Values.gateway_external_ip }}/32
  serviceSelector:
    matchLabels:
      vlan: "{{ .Values.vlan_id }}"
      app: "{{ .Values.application_name }}"
