---
# HTTP Route for the application
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-{{ .Values.application_name }}
  namespace: "{{ .Values.namespace }}"
spec:
  parentRefs:
    - name: gw-{{ .Values.application_name }}
      sectionName: https-{{ .Values.application_name }}
  hostnames:
    - "{{ .Values.host }}"
  rules:
    - backendRefs:
        - name: "{{ .Values.service_name }}"
          namespace: "{{ .Values.namespace }}"
          port: {{ .Values.service_port }}
