---
# Sets up the ingress for argocd
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: https://github.com/it-dfl/homelab.git
      targetRevision: HEAD
      path: argocd/prod/argocd-gateway
      helm:
        valueFiles:
          - $private_repo/argocd/prod/argocd-gateway/values.yaml
    - repoURL: https://github.com/it-dfl/homelab-private.git
      targetRevision: HEAD
      ref: private_repo
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true