---
# Sets up the cert-manager lets encrypt cluster issuers
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://github.com/it-dfl/homelab.git
      targetRevision: HEAD
      path: argocd/prod/cert-manager-issuers
      helm:
        valueFiles: # Email is in the private repo
          - $private_repo/argocd/prod/cert-manager/issuer-values.yaml
    - repoURL: https://github.com/it-dfl/homelab-private.git
      targetRevision: HEAD
      ref: private_repo
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true