apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.9.1
      helm:
        values: |
          defaultSettings:
            defaultDataPath: "/var/mnt/storage-data"
            defaultReplicaCount: 2
          preUpgradeChecker:
            jobEnabled: false
        valueFiles: # Ingress settings are in the private repo
          - $private_repo/argocd/prod/app-of-apps/longhorn-values.yaml
    - repoURL: https://github.com/it-dfl/homelab-private.git
      targetRevision: HEAD
      ref: private_repo
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true