---
# Operator for samba deployments
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: samba-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  project: default
  source:
    repoURL: https://github.com/samba-in-kubernetes/samba-operator.git
    targetRevision: v0.6
    path: config/default
  destination:
    server: https://kubernetes.default.svc
    namespace: samba-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
