apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  sources:
    - chart: vaultwarden
      repoURL: https://guerzon.github.io/vaultwarden
      targetRevision: 0.34.3
      helm:
        values: |
          signupsAllowed: false
          podAnnotations:
            k8s.v1.cni.cncf.io/networks: vaultwarden-static
        valueFiles: # Multus CNI and domain are in the private repo
          - $private_repo/argocd/prod/app-of-apps/vaultwarden.yaml
    - repoURL: https://github.com/it-dfl/homelab-private.git
      targetRevision: HEAD
      ref: private_repo
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true