---
# Sets up the gateway api for  vaultwarden
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: default
  sources:
    - repoURL: https://github.com/it-dfl/homelab.git
      targetRevision: HEAD
      path: argocd/prod/gateway-api-static-vlan-gateway
      helm:
        valueFiles: # all default overrides are in the private repo
          - $private_repo/argocd/prod/app-of-apps/vaultwarden-gateway.yaml
    - repoURL: https://github.com/it-dfl/homelab-private.git
      targetRevision: HEAD
      ref: private_repo
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
